apiVersion: batch/v1
kind: Job
metadata:
  name: sync-s3-bucket
spec:
  template:
    spec:
      containers:
      - name: s3-sync
        image: amazon/aws-cli:latest
        command: ["/bin/sh", "-c"]
        args:
          - aws s3 sync /workspace/ s3://web-page-lambda --delete;
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret_access_key
        - name: AWS_DEFAULT_REGION
          value: "us-west-2"  # Ajuste para a região do seu bucket S3
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: workspace
        emptyDir: {}
  backoffLimit: 3
