apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  access_key_id: QUtJQTJMSVAySVkzUU9QM1o1NDM=
  secret_access_key: NXkweGNoS3p5WWRoK1RuSWtjc3BHWXAxQm5HSmhJSnl6UTJBeTlhSA==